//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class DolazakOdlazak
    {
        public short DolazakOdlazakID { get; set; }
        public Nullable<System.TimeSpan> GornjaGranicaDolaska { get; set; }
        public Nullable<System.TimeSpan> DonjaGranicaDolaska { get; set; }
        public Nullable<System.TimeSpan> GornjaGranicaOdlaska { get; set; }
        public Nullable<System.TimeSpan> DonjaGranicaOdlaska { get; set; }
    }
}
