//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupaRadnik
    {
        public short GrupaRadnikID { get; set; }
        public short GrupaID { get; set; }
        public short RadnikID { get; set; }
        public Nullable<bool> Vođa { get; set; }
        public Nullable<System.DateTime> DatumOd { get; set; }
        public Nullable<System.DateTime> DatumDo { get; set; }
    
        public virtual Grupe Grupe { get; set; }
        public virtual Radnik Radnik { get; set; }
    }
}
