//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LMContext : DbContext
    {
        public LMContext()
            : base("name=LMContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DolazakOdlazak> DolazakOdlazaks { get; set; }
        public virtual DbSet<EvidencijaRada> EvidencijaRadas { get; set; }
        public virtual DbSet<GodisnjiOdmor> GodisnjiOdmors { get; set; }
        public virtual DbSet<GrupaRadnik> GrupaRadniks { get; set; }
        public virtual DbSet<GrupaZaDorucak> GrupaZaDorucaks { get; set; }
        public virtual DbSet<Grupe> Grupes { get; set; }
        public virtual DbSet<Izlaz> Izlazs { get; set; }
        public virtual DbSet<NadredjeniRadnik> NadredjeniRadniks { get; set; }
        public virtual DbSet<NeradniDani> NeradniDanis { get; set; }
        public virtual DbSet<Radnik> Radniks { get; set; }
        public virtual DbSet<RadnikGrupaZaDorucak> RadnikGrupaZaDorucaks { get; set; }
        public virtual DbSet<RadnikRola> RadnikRolas { get; set; }
        public virtual DbSet<RadnikUser> RadnikUsers { get; set; }
        public virtual DbSet<SadrzajObavjestenja> SadrzajObavjestenjas { get; set; }
        public virtual DbSet<Sektor> Sektors { get; set; }
        public virtual DbSet<Slika> Slikas { get; set; }
        public virtual DbSet<SluzbeniPut> SluzbeniPuts { get; set; }
        public virtual DbSet<TerminiZaDorucak> TerminiZaDorucaks { get; set; }
        public virtual DbSet<Tip> Tips { get; set; }
        public virtual DbSet<TipGrupe> TipGrupes { get; set; }
        public virtual DbSet<TipObavjestenja> TipObavjestenjas { get; set; }
        public virtual DbSet<TipPauze> TipPauzes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VrijemePauze> VrijemePauzes { get; set; }
        public virtual DbSet<VrijemeZaposlenja> VrijemeZaposlenjas { get; set; }
        public virtual DbSet<WorkTime> WorkTimes { get; set; }
        public virtual DbSet<RadnoVrijeme> RadnoVrijemes { get; set; }
        public virtual DbSet<Rola> Rolas { get; set; }
        public virtual DbSet<Obavjestenje> Obavjestenjes { get; set; }
    }
}
