//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Radnik()
        {
            this.EvidencijaRadas = new HashSet<EvidencijaRada>();
            this.GodisnjiOdmors = new HashSet<GodisnjiOdmor>();
            this.GrupaRadniks = new HashSet<GrupaRadnik>();
            this.NadredjeniRadniks = new HashSet<NadredjeniRadnik>();
            this.NadredjeniRadniks1 = new HashSet<NadredjeniRadnik>();
            this.RadnikGrupaZaDorucaks = new HashSet<RadnikGrupaZaDorucak>();
            this.RadnikRolas = new HashSet<RadnikRola>();
            this.RadnikUsers = new HashSet<RadnikUser>();
            this.SadrzajObavjestenjas = new HashSet<SadrzajObavjestenja>();
            this.SluzbeniPuts = new HashSet<SluzbeniPut>();
            this.VrijemeZaposlenjas = new HashSet<VrijemeZaposlenja>();
            this.Obavjestenjes = new HashSet<Obavjestenje>();
            this.PrimljenaObavjestenje = new HashSet<Obavjestenje>();
        }
    
        public short RadnikID { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<byte> SektorID { get; set; }
        public string DomenskoIme { get; set; }
        public string EmailAdresa { get; set; }
        public string Lozinka { get; set; }
        public Nullable<short> SlikaID { get; set; }
        public string BrojTelefona { get; set; }
        public string Pol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvidencijaRada> EvidencijaRadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GodisnjiOdmor> GodisnjiOdmors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupaRadnik> GrupaRadniks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NadredjeniRadnik> NadredjeniRadniks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NadredjeniRadnik> NadredjeniRadniks1 { get; set; }
        public virtual Slika Slika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RadnikGrupaZaDorucak> RadnikGrupaZaDorucaks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RadnikRola> RadnikRolas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RadnikUser> RadnikUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SadrzajObavjestenja> SadrzajObavjestenjas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SluzbeniPut> SluzbeniPuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VrijemeZaposlenja> VrijemeZaposlenjas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obavjestenje> Obavjestenjes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obavjestenje> PrimljenaObavjestenje { get; set; }
    }
}
