//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadnoVrijeme
    {
        public byte RadnoVrijemeID { get; set; }
        public byte Mjesec { get; set; }
        public byte RadnihSatiUMjesecu { get; set; }
    }
}
