//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class SadrzajObavjestenja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SadrzajObavjestenja()
        {
            this.Obavjestenjes = new HashSet<Obavjestenje>();
        }
    
        public short SadrzajObavjestenjaID { get; set; }
        public string TextObavjestenja { get; set; }
        public Nullable<short> RadnikID { get; set; }
        public Nullable<System.DateTime> DatumOd { get; set; }
        public Nullable<System.DateTime> DatumDo { get; set; }
    
        public virtual Radnik Radnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obavjestenje> Obavjestenjes { get; set; }
    }
}
