//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminiZaDorucak
    {
        public short TerminiZaDorucakID { get; set; }
        public short GrupaZaDorucakID { get; set; }
        public System.DateTime DatumOd { get; set; }
        public System.DateTime DatumDo { get; set; }
        public System.TimeSpan VrijemPocetka { get; set; }
    
        public virtual GrupaZaDorucak GrupaZaDorucak { get; set; }
    }
}
