//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipObavjestenja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipObavjestenja()
        {
            this.Obavjestenjes = new HashSet<Obavjestenje>();
        }
    
        public short TipObavjestenjaID { get; set; }
        public string Naziv { get; set; }
        public string OpisObavjestenja { get; set; }
        public Nullable<bool> Odgovor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obavjestenje> Obavjestenjes { get; set; }
    }
}
