//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class VrijemePauze
    {
        public byte VrijemePauzeID { get; set; }
        public byte TipPauzeID { get; set; }
        public byte PauzaMinute { get; set; }
        public Nullable<System.TimeSpan> VrijemePauzeOd { get; set; }
        public Nullable<System.TimeSpan> VrijemePauzeDo { get; set; }
    
        public virtual TipPauze TipPauze { get; set; }
    }
}
