//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkTime
    {
        public short WorkTimeID { get; set; }
        public short UserID { get; set; }
        public System.DateTime StartDate { get; set; }
        public string InTimeText { get; set; }
        public string OutTimeText { get; set; }
        public Nullable<System.TimeSpan> InTime { get; set; }
        public Nullable<System.TimeSpan> OutTime { get; set; }
        public byte IzlazID { get; set; }
    
        public virtual Izlaz Izlaz { get; set; }
        public virtual User User { get; set; }
    }
}
